# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deno

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        deno: ["1.7.0"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: deno_postgres
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Check formatting
        run: deno fmt --check

      - name: Check lint
        run: deno lint --unstable

      - name: Run tests
        env:
          PGDATABASE: deno_postgres
          PGPASSWORD: test
          PGUSER: test
        run: deno test --allow-net --allow-env --allow-read=tests/config.json test.ts
